import torch
import torch.nn as nn
import unittest

from chainer_compiler.elichika.testtools import generate_id2type_from_forward
from chainer_compiler.elichika.testtools import type_inference_tools

from testcases.pytorch.fast_neural_style import gen_TransformerNet_model


class TestTransformerNet(unittest.TestCase):
    def test_TransformerNet(self):
        type_inference_tools.reset_state()

        model, forward_args = gen_TransformerNet_model()
        id2type = generate_id2type_from_forward(model, forward_args)

        # === BEGIN ASSERTIONS for TransformerNet ===
        # === function forward ===
        self.assertEqual(str(id2type[8]), "torch.Tensor(float32, (5, 32, 16, 16))")	# Name y (line 2)
        self.assertEqual(str(id2type[10]), "torch.Tensor(float32, (5, 32, 16, 16))")	# Call self.relu(self.in1(self.conv1(X))) (line 2)
        self.assertEqual(str(id2type[12]), "class TransformerNet")	# Name self (line 2)
        self.assertEqual(str(id2type[15]), "torch.Tensor(float32, (5, 32, 16, 16))")	# Call self.in1(self.conv1(X)) (line 2)
        self.assertEqual(str(id2type[17]), "class TransformerNet")	# Name self (line 2)
        self.assertEqual(str(id2type[20]), "torch.Tensor(float32, (5, 32, 16, 16))")	# Call self.conv1(X) (line 2)
        self.assertEqual(str(id2type[22]), "class TransformerNet")	# Name self (line 2)
        self.assertEqual(str(id2type[25]), "torch.Tensor(float32, (5, 3, 16, 16))")	# Name X (line 2)
        self.assertEqual(str(id2type[28]), "torch.Tensor(float32, (5, 64, 8, 8))")	# Name y (line 3)
        self.assertEqual(str(id2type[30]), "torch.Tensor(float32, (5, 64, 8, 8))")	# Call self.relu(self.in2(self.conv2(y))) (line 3)
        self.assertEqual(str(id2type[32]), "class TransformerNet")	# Name self (line 3)
        self.assertEqual(str(id2type[35]), "torch.Tensor(float32, (5, 64, 8, 8))")	# Call self.in2(self.conv2(y)) (line 3)
        self.assertEqual(str(id2type[37]), "class TransformerNet")	# Name self (line 3)
        self.assertEqual(str(id2type[40]), "torch.Tensor(float32, (5, 64, 8, 8))")	# Call self.conv2(y) (line 3)
        self.assertEqual(str(id2type[42]), "class TransformerNet")	# Name self (line 3)
        self.assertEqual(str(id2type[45]), "torch.Tensor(float32, (5, 32, 16, 16))")	# Name y (line 3)
        self.assertEqual(str(id2type[48]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 4)
        self.assertEqual(str(id2type[50]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.relu(self.in3(self.conv3(y))) (line 4)
        self.assertEqual(str(id2type[52]), "class TransformerNet")	# Name self (line 4)
        self.assertEqual(str(id2type[55]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in3(self.conv3(y)) (line 4)
        self.assertEqual(str(id2type[57]), "class TransformerNet")	# Name self (line 4)
        self.assertEqual(str(id2type[60]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv3(y) (line 4)
        self.assertEqual(str(id2type[62]), "class TransformerNet")	# Name self (line 4)
        self.assertEqual(str(id2type[65]), "torch.Tensor(float32, (5, 64, 8, 8))")	# Name y (line 4)
        self.assertEqual(str(id2type[68]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 5)
        self.assertEqual(str(id2type[70]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.res1(y) (line 5)
        self.assertEqual(str(id2type[72]), "class TransformerNet")	# Name self (line 5)
        self.assertEqual(str(id2type[75]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 5)
        self.assertEqual(str(id2type[78]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 6)
        self.assertEqual(str(id2type[80]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.res2(y) (line 6)
        self.assertEqual(str(id2type[82]), "class TransformerNet")	# Name self (line 6)
        self.assertEqual(str(id2type[85]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 6)
        self.assertEqual(str(id2type[88]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 7)
        self.assertEqual(str(id2type[90]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.res3(y) (line 7)
        self.assertEqual(str(id2type[92]), "class TransformerNet")	# Name self (line 7)
        self.assertEqual(str(id2type[95]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 7)
        self.assertEqual(str(id2type[98]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 8)
        self.assertEqual(str(id2type[100]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.res4(y) (line 8)
        self.assertEqual(str(id2type[102]), "class TransformerNet")	# Name self (line 8)
        self.assertEqual(str(id2type[105]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 8)
        self.assertEqual(str(id2type[108]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 9)
        self.assertEqual(str(id2type[110]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.res5(y) (line 9)
        self.assertEqual(str(id2type[112]), "class TransformerNet")	# Name self (line 9)
        self.assertEqual(str(id2type[115]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 9)
        self.assertEqual(str(id2type[118]), "torch.Tensor(float32, (5, 64, None, None))")	# Name y (line 10)
        self.assertEqual(str(id2type[120]), "torch.Tensor(float32, (5, 64, None, None))")	# Call self.relu(self.in4(self.deconv1(y))) (line 10)
        self.assertEqual(str(id2type[122]), "class TransformerNet")	# Name self (line 10)
        self.assertEqual(str(id2type[125]), "torch.Tensor(float32, (5, 64, None, None))")	# Call self.in4(self.deconv1(y)) (line 10)
        self.assertEqual(str(id2type[127]), "class TransformerNet")	# Name self (line 10)
        self.assertEqual(str(id2type[130]), "torch.Tensor(float32, (5, 64, None, None))")	# Call self.deconv1(y) (line 10)
        self.assertEqual(str(id2type[132]), "class TransformerNet")	# Name self (line 10)
        self.assertEqual(str(id2type[135]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name y (line 10)
        self.assertEqual(str(id2type[138]), "torch.Tensor(float32, (5, 32, None, None))")	# Name y (line 11)
        self.assertEqual(str(id2type[140]), "torch.Tensor(float32, (5, 32, None, None))")	# Call self.relu(self.in5(self.deconv2(y))) (line 11)
        self.assertEqual(str(id2type[142]), "class TransformerNet")	# Name self (line 11)
        self.assertEqual(str(id2type[145]), "torch.Tensor(float32, (5, 32, None, None))")	# Call self.in5(self.deconv2(y)) (line 11)
        self.assertEqual(str(id2type[147]), "class TransformerNet")	# Name self (line 11)
        self.assertEqual(str(id2type[150]), "torch.Tensor(float32, (5, 32, None, None))")	# Call self.deconv2(y) (line 11)
        self.assertEqual(str(id2type[152]), "class TransformerNet")	# Name self (line 11)
        self.assertEqual(str(id2type[155]), "torch.Tensor(float32, (5, 64, None, None))")	# Name y (line 11)
        self.assertEqual(str(id2type[158]), "torch.Tensor(float32, (5, 3, None, None))")	# Name y (line 12)
        self.assertEqual(str(id2type[160]), "torch.Tensor(float32, (5, 3, None, None))")	# Call self.deconv3(y) (line 12)
        self.assertEqual(str(id2type[162]), "class TransformerNet")	# Name self (line 12)
        self.assertEqual(str(id2type[165]), "torch.Tensor(float32, (5, 32, None, None))")	# Name y (line 12)
        self.assertEqual(str(id2type[168]), "torch.Tensor(float32, (5, 3, None, None))")	# Name y (line 13)
        # === function forward ===
        self.assertEqual(str(id2type[177]), "torch.Tensor(float32, (5, 3, 24, 24))")	# Name out (line 2)
        self.assertEqual(str(id2type[179]), "torch.Tensor(float32, (5, 3, 24, 24))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[181]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[184]), "torch.Tensor(float32, (5, 3, 16, 16))")	# Name x (line 2)
        self.assertEqual(str(id2type[187]), "torch.Tensor(float32, (5, 32, 16, 16))")	# Name out (line 3)
        self.assertEqual(str(id2type[189]), "torch.Tensor(float32, (5, 32, 16, 16))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[191]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[194]), "torch.Tensor(float32, (5, 3, 24, 24))")	# Name out (line 3)
        self.assertEqual(str(id2type[197]), "torch.Tensor(float32, (5, 32, 16, 16))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[206]), "torch.Tensor(float32, (5, 32, 18, 18))")	# Name out (line 2)
        self.assertEqual(str(id2type[208]), "torch.Tensor(float32, (5, 32, 18, 18))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[210]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[213]), "torch.Tensor(float32, (5, 32, 16, 16))")	# Name x (line 2)
        self.assertEqual(str(id2type[216]), "torch.Tensor(float32, (5, 64, 8, 8))")	# Name out (line 3)
        self.assertEqual(str(id2type[218]), "torch.Tensor(float32, (5, 64, 8, 8))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[220]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[223]), "torch.Tensor(float32, (5, 32, 18, 18))")	# Name out (line 3)
        self.assertEqual(str(id2type[226]), "torch.Tensor(float32, (5, 64, 8, 8))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[235]), "torch.Tensor(float32, (5, 64, 10, 10))")	# Name out (line 2)
        self.assertEqual(str(id2type[237]), "torch.Tensor(float32, (5, 64, 10, 10))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[239]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[242]), "torch.Tensor(float32, (5, 64, 8, 8))")	# Name x (line 2)
        self.assertEqual(str(id2type[245]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[247]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[249]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[252]), "torch.Tensor(float32, (5, 64, 10, 10))")	# Name out (line 3)
        self.assertEqual(str(id2type[255]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[264]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 2)
        self.assertEqual(str(id2type[266]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[269]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[271]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.relu(self.in1(self.conv1(x))) (line 3)
        self.assertEqual(str(id2type[273]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[276]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in1(self.conv1(x)) (line 3)
        self.assertEqual(str(id2type[278]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[281]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv1(x) (line 3)
        self.assertEqual(str(id2type[283]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[286]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 3)
        self.assertEqual(str(id2type[289]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[291]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in2(self.conv2(out)) (line 4)
        self.assertEqual(str(id2type[293]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[296]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2(out) (line 4)
        self.assertEqual(str(id2type[298]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[301]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[304]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[306]), "torch.Tensor(float32, (5, 128, 4, 4))")	# BinOp out + residual (line 5)
        self.assertEqual(str(id2type[307]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[310]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 5)
        self.assertEqual(str(id2type[313]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 6)
        # === function forward ===
        self.assertEqual(str(id2type[322]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[324]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[326]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[329]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[332]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[334]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[336]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[339]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[342]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[351]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[353]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[355]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[358]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[361]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[363]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[365]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[368]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[371]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[380]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 2)
        self.assertEqual(str(id2type[382]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[385]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[387]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.relu(self.in1(self.conv1(x))) (line 3)
        self.assertEqual(str(id2type[389]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[392]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in1(self.conv1(x)) (line 3)
        self.assertEqual(str(id2type[394]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[397]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv1(x) (line 3)
        self.assertEqual(str(id2type[399]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[402]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 3)
        self.assertEqual(str(id2type[405]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[407]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in2(self.conv2(out)) (line 4)
        self.assertEqual(str(id2type[409]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[412]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2(out) (line 4)
        self.assertEqual(str(id2type[414]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[417]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[420]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[422]), "torch.Tensor(float32, (5, 128, 4, 4))")	# BinOp out + residual (line 5)
        self.assertEqual(str(id2type[423]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[426]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 5)
        self.assertEqual(str(id2type[429]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 6)
        # === function forward ===
        self.assertEqual(str(id2type[438]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[440]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[442]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[445]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[448]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[450]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[452]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[455]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[458]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[467]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[469]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[471]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[474]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[477]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[479]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[481]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[484]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[487]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[496]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 2)
        self.assertEqual(str(id2type[498]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[501]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[503]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.relu(self.in1(self.conv1(x))) (line 3)
        self.assertEqual(str(id2type[505]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[508]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in1(self.conv1(x)) (line 3)
        self.assertEqual(str(id2type[510]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[513]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv1(x) (line 3)
        self.assertEqual(str(id2type[515]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[518]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 3)
        self.assertEqual(str(id2type[521]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[523]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in2(self.conv2(out)) (line 4)
        self.assertEqual(str(id2type[525]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[528]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2(out) (line 4)
        self.assertEqual(str(id2type[530]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[533]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[536]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[538]), "torch.Tensor(float32, (5, 128, 4, 4))")	# BinOp out + residual (line 5)
        self.assertEqual(str(id2type[539]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[542]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 5)
        self.assertEqual(str(id2type[545]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 6)
        # === function forward ===
        self.assertEqual(str(id2type[554]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[556]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[558]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[561]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[564]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[566]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[568]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[571]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[574]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[583]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[585]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[587]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[590]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[593]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[595]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[597]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[600]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[603]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[612]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 2)
        self.assertEqual(str(id2type[614]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[617]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[619]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.relu(self.in1(self.conv1(x))) (line 3)
        self.assertEqual(str(id2type[621]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[624]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in1(self.conv1(x)) (line 3)
        self.assertEqual(str(id2type[626]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[629]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv1(x) (line 3)
        self.assertEqual(str(id2type[631]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[634]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 3)
        self.assertEqual(str(id2type[637]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[639]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in2(self.conv2(out)) (line 4)
        self.assertEqual(str(id2type[641]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[644]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2(out) (line 4)
        self.assertEqual(str(id2type[646]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[649]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[652]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[654]), "torch.Tensor(float32, (5, 128, 4, 4))")	# BinOp out + residual (line 5)
        self.assertEqual(str(id2type[655]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[658]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 5)
        self.assertEqual(str(id2type[661]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 6)
        # === function forward ===
        self.assertEqual(str(id2type[670]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[672]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[674]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[677]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[680]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[682]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[684]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[687]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[690]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[699]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[701]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[703]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[706]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[709]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[711]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[713]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[716]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[719]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[728]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 2)
        self.assertEqual(str(id2type[730]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[733]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[735]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.relu(self.in1(self.conv1(x))) (line 3)
        self.assertEqual(str(id2type[737]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[740]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in1(self.conv1(x)) (line 3)
        self.assertEqual(str(id2type[742]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[745]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv1(x) (line 3)
        self.assertEqual(str(id2type[747]), "class ResidualBlock")	# Name self (line 3)
        self.assertEqual(str(id2type[750]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 3)
        self.assertEqual(str(id2type[753]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[755]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.in2(self.conv2(out)) (line 4)
        self.assertEqual(str(id2type[757]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[760]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2(out) (line 4)
        self.assertEqual(str(id2type[762]), "class ResidualBlock")	# Name self (line 4)
        self.assertEqual(str(id2type[765]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        self.assertEqual(str(id2type[768]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[770]), "torch.Tensor(float32, (5, 128, 4, 4))")	# BinOp out + residual (line 5)
        self.assertEqual(str(id2type[771]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 5)
        self.assertEqual(str(id2type[774]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name residual (line 5)
        self.assertEqual(str(id2type[777]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 6)
        # === function forward ===
        self.assertEqual(str(id2type[786]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[788]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[790]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[793]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[796]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[798]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[800]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[803]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[806]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[815]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 2)
        self.assertEqual(str(id2type[817]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[819]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[822]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[825]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 3)
        self.assertEqual(str(id2type[827]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[829]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[832]), "torch.Tensor(float32, (5, 128, 6, 6))")	# Name out (line 3)
        self.assertEqual(str(id2type[835]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name out (line 4)
        # === function forward ===
        self.assertEqual(str(id2type[844]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x_in (line 2)
        self.assertEqual(str(id2type[846]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x (line 2)
        self.assertEqual(str(id2type[849]), "int")	# Attribute self.upsample (line 3)
        self.assertEqual(str(id2type[850]), "class UpsampleConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[854]), "torch.Tensor(float32, (5, 128, 8, 8))")	# Name x_in (line 4)
        self.assertEqual(str(id2type[856]), "torch.Tensor(float32, (5, 128, 8, 8))")	# Call torch.nn.functional.interpolate(x_in, mode='nearest', scale_factor=self.upsample) (line 4)
        self.assertEqual(str(id2type[858]), "class module")	# Attribute torch.nn.functional (line 4)
        self.assertEqual(str(id2type[859]), "class module")	# Attribute torch.nn (line 4)
        self.assertEqual(str(id2type[865]), "torch.Tensor(float32, (5, 128, 4, 4))")	# Name x_in (line 4)
        self.assertEqual(str(id2type[868]), "string")	# Constant 'nearest' (line 4)
        self.assertEqual(str(id2type[870]), "int")	# Attribute self.upsample (line 4)
        self.assertEqual(str(id2type[871]), "class UpsampleConvLayer")	# Name self (line 4)
        self.assertEqual(str(id2type[875]), "torch.Tensor(float32, (5, 128, None, None))")	# Name out (line 5)
        self.assertEqual(str(id2type[877]), "torch.Tensor(float32, (5, 128, None, None))")	# Call self.reflection_pad(x_in) (line 5)
        self.assertEqual(str(id2type[879]), "class UpsampleConvLayer")	# Name self (line 5)
        self.assertEqual(str(id2type[882]), "torch.Tensor(float32, (5, 128, None, None))")	# Name x_in (line 5)
        self.assertEqual(str(id2type[885]), "torch.Tensor(float32, (5, 64, None, None))")	# Name out (line 6)
        self.assertEqual(str(id2type[887]), "torch.Tensor(float32, (5, 64, None, None))")	# Call self.conv2d(out) (line 6)
        self.assertEqual(str(id2type[889]), "class UpsampleConvLayer")	# Name self (line 6)
        self.assertEqual(str(id2type[892]), "torch.Tensor(float32, (5, 128, None, None))")	# Name out (line 6)
        self.assertEqual(str(id2type[895]), "torch.Tensor(float32, (5, 64, None, None))")	# Name out (line 7)
        # === function forward ===
        self.assertEqual(str(id2type[904]), "torch.Tensor(float32, (5, 64, None, None))")	# Name x_in (line 2)
        self.assertEqual(str(id2type[906]), "torch.Tensor(float32, (5, 64, None, None))")	# Name x (line 2)
        self.assertEqual(str(id2type[909]), "int")	# Attribute self.upsample (line 3)
        self.assertEqual(str(id2type[910]), "class UpsampleConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[914]), "torch.Tensor(float32, (5, 64, None, None))")	# Name x_in (line 4)
        self.assertEqual(str(id2type[916]), "torch.Tensor(float32, (5, 64, None, None))")	# Call torch.nn.functional.interpolate(x_in, mode='nearest', scale_factor=self.upsample) (line 4)
        self.assertEqual(str(id2type[918]), "class module")	# Attribute torch.nn.functional (line 4)
        self.assertEqual(str(id2type[919]), "class module")	# Attribute torch.nn (line 4)
        self.assertEqual(str(id2type[925]), "torch.Tensor(float32, (5, 64, None, None))")	# Name x_in (line 4)
        self.assertEqual(str(id2type[928]), "string")	# Constant 'nearest' (line 4)
        self.assertEqual(str(id2type[930]), "int")	# Attribute self.upsample (line 4)
        self.assertEqual(str(id2type[931]), "class UpsampleConvLayer")	# Name self (line 4)
        self.assertEqual(str(id2type[935]), "torch.Tensor(float32, (5, 64, None, None))")	# Name out (line 5)
        self.assertEqual(str(id2type[937]), "torch.Tensor(float32, (5, 64, None, None))")	# Call self.reflection_pad(x_in) (line 5)
        self.assertEqual(str(id2type[939]), "class UpsampleConvLayer")	# Name self (line 5)
        self.assertEqual(str(id2type[942]), "torch.Tensor(float32, (5, 64, None, None))")	# Name x_in (line 5)
        self.assertEqual(str(id2type[945]), "torch.Tensor(float32, (5, 32, None, None))")	# Name out (line 6)
        self.assertEqual(str(id2type[947]), "torch.Tensor(float32, (5, 32, None, None))")	# Call self.conv2d(out) (line 6)
        self.assertEqual(str(id2type[949]), "class UpsampleConvLayer")	# Name self (line 6)
        self.assertEqual(str(id2type[952]), "torch.Tensor(float32, (5, 64, None, None))")	# Name out (line 6)
        self.assertEqual(str(id2type[955]), "torch.Tensor(float32, (5, 32, None, None))")	# Name out (line 7)
        # === function forward ===
        self.assertEqual(str(id2type[964]), "torch.Tensor(float32, (5, 32, None, None))")	# Name out (line 2)
        self.assertEqual(str(id2type[966]), "torch.Tensor(float32, (5, 32, None, None))")	# Call self.reflection_pad(x) (line 2)
        self.assertEqual(str(id2type[968]), "class ConvLayer")	# Name self (line 2)
        self.assertEqual(str(id2type[971]), "torch.Tensor(float32, (5, 32, None, None))")	# Name x (line 2)
        self.assertEqual(str(id2type[974]), "torch.Tensor(float32, (5, 3, None, None))")	# Name out (line 3)
        self.assertEqual(str(id2type[976]), "torch.Tensor(float32, (5, 3, None, None))")	# Call self.conv2d(out) (line 3)
        self.assertEqual(str(id2type[978]), "class ConvLayer")	# Name self (line 3)
        self.assertEqual(str(id2type[981]), "torch.Tensor(float32, (5, 32, None, None))")	# Name out (line 3)
        self.assertEqual(str(id2type[984]), "torch.Tensor(float32, (5, 3, None, None))")	# Name out (line 4)
        # === END ASSERTIONS for TransformerNet ===


def main():
    unittest.main()

if __name__ == '__main__':
    main()
