FROM nvidia/cuda:10.0-cudnn7-devel

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    build-essential \
    cmake \
    curl \
    g++ \
    git \
    git \
    libblas-dev \
    libblas3 \
    libopencv-dev \
    libprotobuf-dev \
    libtinfo-dev \
    libtool \
    llvm-6.0-dev \
    make \
    ninja-build \
    pkg-config \
    protobuf-compiler \
    python3-dev \
    python3-pip \
    python3-pytest \
    python3-setuptools \
    python3-wheel \
    unzip \
    wget \
    zlib1g \
    zlib1g-dev \
    && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

RUN CHAINER_BUILD_CHAINERX=1 CHAINERX_BUILD_CUDA=1 pip3 install --no-cache-dir cupy-cuda100==6.0.0b1 chainer==6.0.0b1

RUN pip3 install gast numpy chainer onnx==1.3.0 onnx_chainer matplotlib Pillow xgboost tornado psutil

COPY tvm_install/ubuntu_install_core.sh /install/ubuntu_install_core.sh
RUN bash /install/ubuntu_install_core.sh

COPY tvm_install/install_tvm_gpu.sh /install/install_tvm_gpu.sh
RUN bash /install/install_tvm_gpu.sh

RUN cd /usr/tvm/build && make install

RUN cd /usr/tvm && \
    cd python && \
    python3 setup.py install --user && \
    cd .. && \
    cd topi/python && \
    python3 setup.py install --user && \
    cd ../.. && \
    cd nnvm/python && \
    python3 setup.py install --user && \
    cd ../..

RUN mkdir -p /usr/tvm/3rdparty/dmlc-core/build && \
    cd /usr/tvm/3rdparty/dmlc-core/build && \
    cmake .. && make && make install

ARG NGRAPH_VERSION="v0.15.0-rc.0"
ARG NGRAPH_INTELGPU_ENABLE="ON"
RUN git clone https://github.com/NervanaSystems/ngraph.git \
    && cd ngraph \
    && git checkout $NGRAPH_VERSION \
    && mkdir build && cd build \
    && cmake .. -DNGRAPH_ONNX_IMPORT_ENABLE=ON -DNGRAPH_USE_PREBUILT_LLVM=ON -DNGRAPH_INTELGPU_ENABLE=$NGRAPH_INTELGPU_ENABLE -DCMAKE_INSTALL_PREFIX=~/ngraph_dist \
    && make -j4 \
    && make install

RUN cd ngraph/python \
    && git clone --recursive https://github.com/pybind/pybind11.git \
    && pip3 install .

RUN git clone https://github.com/NervanaSystems/ngraph-onnx/ \
    && cd ngraph-onnx \
    && pip3 install .

RUN git clone https://%GITHUB_AUTH_TOKEN%:x-oauth-basic@github.com/pfnet-research/chainer-compiler.git
RUN cd /chainer-compiler && git submodule update --init
RUN mkdir -p chainer-compiler/build && \
    cd chainer-compiler/build && \
    cmake .. \
    -G Ninja \
    -DCHAINER_COMPILER_BUILD_CUDA=ON \
    -DCHAINER_COMPILER_ENABLE_NVTX=ON \
    -DCHAINER_COMPILER_ENABLE_NVRTC=ON \
    -DCHAINER_COMPILER_ENABLE_CUDNN=ON \
    -DCHAINER_COMPILER_ENABLE_OPENCV=ON \
    -DCHAINER_COMPILER_ENABLE_PYTHON=ON \
    -DCHAINER_COMPILER_NGRAPH_DIR=$HOME/ngraph_dist \
    -DPYTHON_EXECUTABLE=/usr/bin/python3 \
    -DCHAINER_COMPILER_ENABLE_TVM=ON \
    -DCHAINERX_BUILD_CUDA=ON \
    -DCHAINERX_BUILD_PYTHON=ON \
    && \
    ninja

# Optional packages.
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    less \
    lv \
    screen \
    vim \
    zsh \
    && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# Environment variables
ENV PYTHONPATH=/usr/tvm/python:/usr/tvm/topi/python:/usr/tvm/nnvm/python/:/usr/tvm/vta/python:${PYTHONPATH}
ENV PATH=/usr/local/nvidia/bin:${PATH}
ENV PATH=/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/compat:/usr/local/nvidia/lib64:/usr/local/lib:${LD_LIBRARY_PATH}
