configs {
  key: "chainer-compiler"
  value {
    requirement {
      cpu: 8
      disk: 50
      memory: 16
      gpu: 1
    }
    time_limit {
      seconds: 3600
    }
    checkout_strategy {
      ignore_gitignore: true
    }
    command: "sh .flexci/run_flexci_tests.sh"
  }
}
configs {
  key: "chainer-compiler.pip"
  value {
    requirement {
      cpu: 8
      disk: 50
      memory: 16
      gpu: 1
    }
    time_limit {
      seconds: 3600
    }
    checkout_strategy {
      ignore_gitignore: true
    }
    command: "sh .flexci/run_flexci_pip_tests.sh"
  }
}
configs {
  key: "chainer-compiler.run-onnx.dldt"
  value {
    requirement {
      cpu: 8
      disk: 10
      memory: 16
    }
    time_limit {
      seconds: 3600
    }
    environment_variables { key: "CHINAER_COMPILER_RUNTIME" value: "dldt" }
    environment_variables { key: "CHINAER_COMPILER_DOCKER_RUNTIME_ARG" value: "" }
    command: "sh .flexci/run_onnx.sh"
  }
}
configs {
  key: "chainer-compiler.run-onnx.ngrp"
  value {
    requirement {
      cpu: 8
      disk: 10
      memory: 16
    }
    time_limit {
      seconds: 3600
    }
    environment_variables { key: "CHINAER_COMPILER_RUNTIME" value: "ngraph" }
    environment_variables { key: "CHINAER_COMPILER_DOCKER_RUNTIME_ARG" value: "" }
    command: "sh .flexci/run_onnx.sh"
  }
}
configs {
  key: "chainer-compiler.run-onnx.oxrt"
  value {
    requirement {
      cpu: 8
      disk: 10
      memory: 16
    }
    time_limit {
      seconds: 3600
    }
    environment_variables { key: "CHINAER_COMPILER_RUNTIME" value: "onnxruntime" }
    environment_variables { key: "CHINAER_COMPILER_DOCKER_RUNTIME_ARG" value: "" }
    command: "sh .flexci/run_onnx.sh"
  }
}
configs {
  key: "chainer-compiler.run-onnx.tvm"
  value {
    requirement {
      cpu: 8
      disk: 10
      memory: 16
      gpu: 1
    }
    time_limit {
      seconds: 3600
    }
    environment_variables { key: "CHINAER_COMPILER_RUNTIME" value: "tvm" }
    environment_variables { key: "CHINAER_COMPILER_DOCKER_RUNTIME_ARG" value: "--runtime=nvidia" }
    command: "sh .flexci/run_onnx.sh"
  }
}
