configs {
  key: "chainer-compiler"
  value {
    requirement {
      cpu: 8
      disk: 10
      memory: 16
      gpu: 1
    }
    time_limit {
      seconds: 3600
    }
    command: "sh .chainerci/run-chainerci-tests.sh"
  }
}
